name: Build and Upload Sourcemaps

on:
  push:
    branches: [main]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Inject & upload sourcemaps to PostHog
        uses: ablaszkiewicz/posthog-cli-github-action@v0.6
        with:
          directory: "./dist"
          cli-token: ${{ secrets.POSTHOG_CLI_TOKEN }}
          env-id: "215564"
